# Generated by Django 2.2.6 on 2019-10-31 23:19

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('hospedajes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='booking',
            name='dni',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='surname',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='daily_import',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='fk_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospedajes_app.City'),
        ),
        migrations.AddField(
            model_name='property',
            name='fk_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='pax',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rental_date',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rental_date',
            name='fk_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospedajes_app.Booking'),
        ),
        migrations.AddField(
            model_name='rental_date',
            name='fk_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospedajes_app.Property'),
        ),
    ]
