# Generated by Django 2.2.6 on 2019-11-01 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospedajes_app', '0002_auto_20191031_2019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rental_Date',
            new_name='RentalDate',
        ),
        migrations.AlterField(
            model_name='property',
            name='fk_city',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospedajes_app.City'),
        ),
        migrations.AlterField(
            model_name='property',
            name='fk_user',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospedajes_app.Host'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default=0, null=True, upload_to=''),
        ),
    ]
