# Generated by Django 2.2.6 on 2019-11-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedajes_app', '0007_auto_20191104_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, upload_to='property_image/'),
        ),
    ]
