# Generated by Django 2.2.6 on 2019-11-05 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospedajes_app', '0009_auto_20191105_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('surname', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('dni', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='surname',
        ),
        migrations.AlterField(
            model_name='rentaldate',
            name='fk_booking',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='hospedajes_app.Booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospedajes_app.User'),
        ),
    ]
