# Generated by Django 2.2.6 on 2019-11-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedajes_app', '0010_auto_20191105_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
