# Generated by Django 2.2.6 on 2019-11-06 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospedajes_app', '0012_auto_20191106_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldate',
            name='fk_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hospedajes_app.Booking'),
        ),
    ]
