# Generated by Django 2.2.6 on 2019-11-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedajes_app', '0014_auto_20191107_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(null=True, upload_to='../media/'),
        ),
    ]
