# Generated by Django 2.2.6 on 2019-11-08 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospedajes_app', '0019_property_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='quantity',
        ),
    ]
