# Generated by Django 2.2.6 on 2019-11-08 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospedajes_app', '0021_comfort'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComfortXProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('comfort', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospedajes_app.Comfort')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hospedajes_app.Property')),
            ],
        ),
    ]
