# Generated by Django 2.2.6 on 2019-11-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedajes_app', '0033_comfort_classname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comfort',
            name='className',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
