# Generated by Django 2.2.6 on 2019-11-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospedajes_app', '0034_auto_20191108_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comfort',
            name='className',
        ),
    ]
