# Generated by Django 2.2.6 on 2019-11-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedajes_app', '0035_remove_comfort_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='comfort',
            name='className',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
