# Generated by Django 2.2.6 on 2019-11-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedajes_app', '0036_comfort_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='className',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
