# Generated by Django 2.2.6 on 2019-11-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedajes_app', '0037_feature_classname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
    ]
