# Generated by Django 2.2.6 on 2019-11-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospedajes_app', '0042_auto_20191115_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dni',
        ),
    ]
