# Generated by Django 2.2.6 on 2019-11-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedajes_app', '0043_remove_profile_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
