# Generated by Django 4.1.1 on 2022-11-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospedajes_app', '0046_booking_property'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='TipoAula',
        ),
        migrations.AlterModelOptions(
            name='tipoaula',
            options={'verbose_name_plural': 'TiposAula'},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='city',
            new_name='tipoAula',
        ),
    ]
