# Generated by Django 4.1.1 on 2022-11-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospedajes_app', '0048_rename_feature_caracteristica_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comfort',
            new_name='Capacidad',
        ),
        migrations.RenameModel(
            old_name='ComfortXProperty',
            new_name='CapacidadXProperty',
        ),
        migrations.AlterModelOptions(
            name='capacidad',
            options={'verbose_name_plural': 'Capacidades'},
        ),
        migrations.AlterModelOptions(
            name='capacidadxproperty',
            options={'verbose_name_plural': 'CapacidadesXProperty'},
        ),
        migrations.RenameField(
            model_name='capacidadxproperty',
            old_name='comfort',
            new_name='capacidad',
        ),
    ]
