# Generated by Django 4.1.1 on 2022-11-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedajes_app', '0050_rename_booking_reserva_alter_reserva_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='hora',
            field=models.TextField(max_length=13, null='True'),
            preserve_default='True',
        ),
    ]
