# Generated by Django 4.1.1 on 2022-11-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedajes_app', '0051_property_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='hora',
            field=models.TextField(max_length=13, null=True),
        ),
    ]
